"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _catalog_grid_bone from './catalog-grid-bone.bones.json'

registerBones({
  "catalog-grid-bone": _catalog_grid_bone,
})
